data_dir: "data/LongSimulated_Data/Data-80/LongSeqs"
result_dir: "results/Data-80/LongSeqs/Clustered"
num_of_seq: 30000
seq_len: 1500
data_instances: 3
runs: 3
path_to_meme: "/s/chromatin/p/nobackup/Saira/motif_databases/JASPAR2024_CORE_non-redundant_pfms.meme"
pairs_file: "clustered_tf_pairs_80.txt"
param_dist:
  lr: [1e-4, 1e-3, 1e-2]
  batch_size: [16, 32, 64]
  linear_layer_size: [256, 512, 1024]
  dropout_rate: [0.1, 0.2, 0.3]
  weight_decay: [0, 1e-4, 1e-3]
  num_multiheads: [2, 4, 8]
  singlehead_size: [32, 64, 128]
  CNN_filters: [[256], [380], [512]]
  CNN_filtersize: [[13], [16], [24]]
  momentum: [0.8, 0.9, 0.99]
  optimizer: ["adam", "sgd"]
